### ISSUE TITLE
Clear difference with postcss-mixins

### ISSUE THREAD

**Issue by ai** [andyjansson/postcss-sassy-mixins#1]
You should write clear what is the difference between this two plugins.

**Comment by andyjansson** [comment]
README.md has been edited and should hopefully reflect the difference between the two plugins.

**Comment by ai** [comment]
Not really, because technically, postcss-mixins use same “syntax” too. Question is only about keywords and brackets.

**Comment by andyjansson** [comment]
That's what syntax is. Syntax != semantics.

**Comment by ai** [comment]
@andyjansson OK :)
