### ISSUE TITLE
Sass VS Scss

### ISSUE THREAD

**Issue by hmalaud** [andyjansson/postcss-sassy-mixins#12]
As per http://sass-lang.com/guide, seems to me the plugin is using Scss syntax, not Sass', which looks like this:
```
=transform($property)
  -webkit-transform: $property
  -ms-transform:     $property
  transform:         $property

.box
  +transform(rotate(30deg))
```

**Comment by andyjansson** [comment]
1. Sass, as in the language, not the syntax. If you want any semblance of sass, you can use [SugarSS](https://github.com/postcss/sugarss).

2. I've described it as *sass-like*. If you want sass, you use sass.
