### ISSUE TITLE
@content fails if no content object is provided

### ISSUE THREAD

**Issue by samvk** [andyjansson/postcss-sassy-mixins#8]
In Sass, `@content` is optional (if you just want what's included). E.g.

```
@mixin hover($color: null) {
    &:hover {
        text-decoration: underline
        color: $color;
        @content;
    }
}
label {
    @include hover(blue);        // no `@content` (i.e. {}) defined`
}
```

This same setup currently errors. At least `@include hover(blue){}` must be written. It would be nice to optionally leave any content off and simply default to having been passed an empty object.

**Comment by andyjansson** [comment]
Thanks. A new version has been published. I'll probably get around to publishing a new major with updated references and code updates in a few days as well.
