### ISSUE TITLE
Support new css "custom properties" as arguments (and default params)

### ISSUE THREAD

**Issue by samvk** [andyjansson/postcss-sassy-mixins#9]
**Request**: Currently it seems only sassy variables (or real values) are allowed as arguments. Doing this:
```
@mixin paint($color){
    color: $color;
}
.icon {@include paint(  var(--color-primary) )}
```
Will return literally `color: var(--color-primary)` rather than extrapolate. 

---

The current workaround is to simply define `$color-primary: var(--color-secondary);` right above and then use this sassy variable within the function.

**Comment by andyjansson** [comment]
Try and add postcss-custom-properties after postcss-sassy-mixins. It should evaluate the return value.

**Comment by samvk** [comment]
My apologies that was exactly it.

Thanks!
